---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
      
  - name: install nginx package
    apt:
      name: nginx
      state: latest

  - name: install git package
    apt:
      name: git
      state: latest
      
  - name: install vim package
    apt:
      name: git
      state: latest

